# Generated by Django 6.0.1 on 2026-01-15 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('climate', models.CharField(max_length=100)),
                ('terrain_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Guild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('special_traits', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('population', models.IntegerField()),
                ('is_safe_from_plague', models.BooleanField(default=False)),
                ('emblem', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Kingdom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('population', models.IntegerField()),
                ('homeland', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wiki.continent')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wiki.location')),
            ],
        ),
        migrations.CreateModel(
            name='Plague',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('history', models.TextField()),
                ('symptomps', models.TextField()),
                ('death', models.IntegerField()),
                ('epicentre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wiki.location')),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('resistance', models.TextField()),
                ('traits', models.TextField()),
                ('ethos', models.TextField()),
                ('homeland', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wiki.continent')),
            ],
        ),
    ]
