# Generated by Django 4.2.25 on 2026-01-16 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('climate', models.CharField(max_length=100)),
                ('terrain_type', models.CharField(max_length=100)),
                ('population', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Kontynent',
                'verbose_name_plural': 'Kontynenty',
                'ordering': ['population'],
            },
        ),
        migrations.CreateModel(
            name='Guild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('special_traits', models.TextField()),
            ],
            options={
                'verbose_name': 'Gildia',
                'verbose_name_plural': 'Gildie',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('effect', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('population', models.IntegerField()),
                ('location_type', models.CharField(max_length=50)),
                ('is_safe_from_plague', models.BooleanField(default=False)),
                ('emblem', models.ImageField(blank=True, null=True, upload_to='emblems/')),
                ('continent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wiki.continent')),
            ],
            options={
                'verbose_name': 'Lokacja',
                'verbose_name_plural': 'Lokacje',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Epicentre',
            fields=[
                ('location_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wiki.location')),
                ('infection_rate', models.IntegerField(help_text='Procent zarażonych (0-100)')),
                ('deaths_here', models.IntegerField(help_text='Ilość zgonów')),
                ('danger_level', models.CharField(choices=[('low', 'Niski'), ('medium', 'Umiarkowany'), ('high', 'Wysoki'), ('deathly', 'Śmiertelny')], default='medium', max_length=20)),
            ],
            options={
                'verbose_name': 'Epicentrum plagi',
                'verbose_name_plural': 'Epicentra plagi',
            },
            bases=('wiki.location',),
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('resistance', models.CharField(max_length=50)),
                ('traits', models.TextField()),
                ('ethos', models.TextField()),
                ('homeland', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wiki.continent')),
            ],
            options={
                'verbose_name': 'Rasa',
                'verbose_name_plural': 'Rasy',
            },
        ),
        migrations.CreateModel(
            name='Plague',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='Opis plagi')),
                ('history', models.TextField(help_text='Historia - jak to wszystko się zaczęło')),
                ('symptomps', models.TextField(help_text='Objawy')),
                ('death', models.IntegerField(help_text='Szacunkowa liczba osób które umarły przez zarażenie')),
                ('epicentre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wiki.location')),
            ],
            options={
                'verbose_name': 'Plaga',
                'verbose_name_plural': 'Informacje o pladze',
            },
        ),
        migrations.CreateModel(
            name='Kingdom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('population', models.IntegerField()),
                ('capital', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wiki.location')),
            ],
            options={
                'verbose_name': 'Królestwo',
                'verbose_name_plural': 'Królestwa',
                'ordering': ['population'],
            },
        ),
    ]
